# Generated by Django 6.1.1 on 2026-09-14 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('adress', models.CharField(max_length=150, verbose_name='Адрес')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('foto', models.ImageField(upload_to='hotels/', verbose_name='Фото')),
                ('reiting', models.IntegerField(verbose_name='ОТ 1 ДО 5 Оценка')),
            ],
            options={
                'verbose_name': 'Отел',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Номер')),
                ('discription', models.CharField(choices=[('massege', 'Стандарт'), ('massege', 'Улушенный'), ('massege', 'Делюкс'), ('massege', 'Сьют'), ('massege', 'Апартаменты')], verbose_name='Тип номера')),
                ('price_for_day', models.IntegerField(verbose_name='Цена за ночь')),
                ('count', models.IntegerField(verbose_name='Количество месть')),
                ('foto', models.ImageField(upload_to='hotels/numbers/', verbose_name='Фото')),
                ('availability', models.BooleanField(default=True, verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата заезда')),
                ('data_out', models.DateField(verbose_name='Дата выезда')),
                ('guest_count', models.IntegerField(verbose_name='Количество гостей')),
                ('endprice', models.IntegerField(verbose_name='Общая цена')),
                ('status', models.BooleanField(default=False, verbose_name='Статус бронирования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('nombers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.numbers', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.IntegerField(verbose_name='Оценка от 1 до 5')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotels', verbose_name='Отель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
